# Generated by Django 3.1.4 on 2020-12-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_order_procuct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procuct',
            new_name='Product',
        ),
    ]
